In [186]:
import pandas as pd
import numpy as np
import datetime

## Dataframe HECHOS

Se carga primero la pestaña de **HECHOS** del archivo homicidios.xlsx

In [142]:
df_hechos = pd.read_excel(r'Datasets/homicidios.xlsx', sheet_name='HECHOS')

In [143]:
df_hechos.head(1)

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO

In [144]:
df_hechos.shape

(696, 21)

## Dataframe VICTIMAS

Se carga la pestaña **VICTIMAS** del archivo homicidio.xlsx

In [145]:
df_victimas=pd.read_excel(r'Datasets/homicidios.xlsx', sheet_name='VICTIMAS')

In [146]:
df_victimas.head(1)

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00

In [147]:
df_victimas.shape

(717, 10)

## Dataframe HOMICIDIOS

Vamos a unir los dos dataframes para poder ver y procesar mejor la información.

In [148]:
df_homicidios = pd.merge(df_hechos, df_victimas, left_on='ID', right_on='ID_hecho')

In [149]:
df_homicidios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     717 non-null    object
 1   N_VICTIMAS             717 non-null    int64
 2   FECHA_x                717 non-null    datetime64[ns]
 3   AAAA_x                 717 non-null    int64
 4   MM_x                   717 non-null    int64
 5   DD_x                   717 non-null    int64
 6   HORA                   717 non-null    object
 7   HH                     717 non-null    object
 8   LUGAR_DEL_HECHO        717 non-null    object
 9   TIPO_DE_CALLE          717 non-null    object
 10  Calle                  716 non-null    object
 11  Altura                 133 non-null    float64
 12  Cruce                  540 non-null    object
 13  Dirección Normalizada  708 non-null    object
 14  COMUNA                 717 non-null    int64
 15  XY (CABA)              717 non-null    object
 16  pos x                  717 non-null    object
 17  pos y                  717 non-null    object
 18  PARTICIPANTES          717 non-null    object
 19  VICTIMA_x              717 non-null    object
 20  ACUSADO                717 non-null    object
 21  ID_hecho               717 non-null    object
 22  FECHA_y                717 non-null    datetime64[ns]
 23  AAAA_y                 717 non-null    int64
 24  MM_y                   717 non-null    int64
 25  DD_y                   717 non-null    int64
 26  ROL                    717 non-null    object
 27  VICTIMA_y              717 non-null    object
 28  SEXO                   717 non-null    object
 29  EDAD                   717 non-null    object
 30  FECHA_FALLECIMIENTO    717 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(8), object(20)
memory usage: 173.8+ KB

In [150]:
df_homicidios.head(1)

,ID,N_VICTIMAS,FECHA_x,AAAA_x,MM_x,DD_x,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,ID_hecho,FECHA_y,AAAA_y,MM_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00

In [151]:
df_homicidios.shape

(717, 31)

In [152]:
df_homicidios.columns

Index(['ID', 'N_VICTIMAS', 'FECHA_x', 'AAAA_x', 'MM_x', 'DD_x', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA_x', 'ACUSADO', 'ID_hecho', 'FECHA_y',
       'AAAA_y', 'MM_y', 'DD_y', 'ROL', 'VICTIMA_y', 'SEXO', 'EDAD',
       'FECHA_FALLECIMIENTO'],
      dtype='object')

Se comienza eliminando la información que no se utilizará o es redundante.

In [154]:
df_homicidios.drop(['ID', 'HH','FECHA_y','AAAA_y', 'MM_y', 'DD_y','XY (CABA)','VICTIMA_y','FECHA_FALLECIMIENTO'],axis=1,inplace=True)

In [155]:
df_homicidios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   N_VICTIMAS             717 non-null    int64
 1   FECHA_x                717 non-null    datetime64[ns]
 2   AAAA_x                 717 non-null    int64
 3   MM_x                   717 non-null    int64
 4   DD_x                   717 non-null    int64
 5   HORA                   717 non-null    object
 6   LUGAR_DEL_HECHO        717 non-null    object
 7   TIPO_DE_CALLE          717 non-null    object
 8   Calle                  716 non-null    object
 9   Altura                 133 non-null    float64
 10  Cruce                  540 non-null    object
 11  Dirección Normalizada  708 non-null    object
 12  COMUNA                 717 non-null    int64
 13  pos x                  717 non-null    object
 14  pos y                  717 non-null    object
 15  PARTICIPANTES          717 non-null    object
 16  VICTIMA_x              717 non-null    object
 17  ACUSADO                717 non-null    object
 18  ID_hecho               717 non-null    object
 19  ROL                    717 non-null    object
 20  SEXO                   717 non-null    object
 21  EDAD                   717 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(15)
memory usage: 123.4+ KB

Movemos la columna *ID_hecho* al principio de todo.

In [156]:
col = df_homicidios.pop('ID_hecho')
df_homicidios.insert(0, col.name, col)

Cambiamos los nombres de las columnas

In [157]:
df_homicidios.columns

Index(['ID_hecho', 'N_VICTIMAS', 'FECHA_x', 'AAAA_x', 'MM_x', 'DD_x', 'HORA',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'pos x', 'pos y', 'PARTICIPANTES',
       'VICTIMA_x', 'ACUSADO', 'ROL', 'SEXO', 'EDAD'],
      dtype='object')

In [158]:
df_homicidios.columns = df_homicidios.columns.str.title()

In [159]:
df_homicidios.rename(columns={'N_Victimas':'Cant_Victimas','Fecha_X':'Fecha', 'Aaaa_X':'Año', 'Mm_X':'Mes', 'Dd_X':'Día', 'Dirección_Normalizada':'Dirección', 'Pos X':'Latitud', 'Pos Y':'Longitud','Victima_X':'Victima','PARTICIPANTES':'Involucrados'}, inplace=True)

In [160]:
df_homicidios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id_Hecho               717 non-null    object
 1   Cant_Victimas          717 non-null    int64
 2   Fecha                  717 non-null    datetime64[ns]
 3   Año                    717 non-null    int64
 4   Mes                    717 non-null    int64
 5   Día                    717 non-null    int64
 6   Hora                   717 non-null    object
 7   Lugar_Del_Hecho        717 non-null    object
 8   Tipo_De_Calle          717 non-null    object
 9   Calle                  716 non-null    object
 10  Altura                 133 non-null    float64
 11  Cruce                  540 non-null    object
 12  Dirección Normalizada  708 non-null    object
 13  Comuna                 717 non-null    int64
 14  Latitud                717 non-null    object
 15  Longitud               717 non-null    object
 16  Participantes          717 non-null    object
 17  Victima                717 non-null    object
 18  Acusado                717 non-null    object
 19  Rol                    717 non-null    object
 20  Sexo                   717 non-null    object
 21  Edad                   717 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(15)
memory usage: 123.4+ KB

Se da un primer vistazo a la cantidad de nulos.

In [161]:
df_homicidios.isnull().sum()

Id_Hecho                   0
Cant_Victimas              0
Fecha                      0
Año                        0
Mes                        0
Día                        0
Hora                       0
Lugar_Del_Hecho            0
Tipo_De_Calle              0
Calle                      1
Altura                   584
Cruce                    177
Dirección Normalizada      9
Comuna                     0
Latitud                    0
Longitud                   0
Participantes              0
Victima                    0
Acusado                    0
Rol                        0
Sexo                       0
Edad                       0
dtype: int64

In [162]:
df_homicidios.columns

Index(['Id_Hecho', 'Cant_Victimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora',
       'Lugar_Del_Hecho', 'Tipo_De_Calle', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'Comuna', 'Latitud', 'Longitud',
       'Participantes', 'Victima', 'Acusado', 'Rol', 'Sexo', 'Edad'],
      dtype='object')

## Transformación de las columnas
Se revisará cada columna para verificar la integridad mínima de los datosy así pasar a la postetiror etapa, en este caso el EDA.

### Id_Hecho

Se verifica que no haya duplicados

In [176]:
df_homicidios['Id_Hecho'].duplicated().sum()

21

En este caso los duplicados se permiten ya que cada clave de identificación de hecho esta relacionada con las víctimas

In [178]:
df_homicidios[df_homicidios['Id_Hecho'].duplicated(keep=False)]

,Id_Hecho,Cant_Victimas,Fecha,Año,Mes,Día,Hora,Lugar_Del_Hecho,Tipo_De_Calle,Calle,...,Dirección Normalizada,Comuna,Latitud,Longitud,Participantes,Victima,Acusado,Rol,Sexo,Edad
29,2016-0041,2,2016-03-29,2016,3,29,11:00:00,AV DIRECTORIO Y RIVERA INDARTE,AVENIDA,DIRECTORIO AV.,...,DIRECTORIO AV. y RIVERA INDARTE AV.,7,-58.460766,-34.633504,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MASCULINO,54
30,2016-0041,2,2016-03-29,2016,3,29,11:00:00,AV DIRECTORIO Y RIVERA INDARTE,AVENIDA,DIRECTORIO AV.,...,DIRECTORIO AV. y RIVERA INDARTE AV.,7,-58.460766,-34.633504,MOTO-CARGAS,MOTO,CARGAS,PASAJERO_ACOMPAÑANTE,MASCULINO,SD
98,2016-0126,2,2016-09-18,2016,9,18,22:45:00,IRIGOYEN Y TINOGASTA,CALLE,IRIGOYEN,...,IRIGOYEN y TINOGASTA,10,-58.525721,-34.621259,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,MASCULINO,37
99,2016-0126,2,2016-09-18,2016,9,18,22:45:00,IRIGOYEN Y TINOGASTA,CALLE,IRIGOYEN,...,IRIGOYEN y TINOGASTA,10,-58.525721,-34.621259,AUTO-CARGAS,AUTO,CARGAS,PASAJERO_ACOMPAÑANTE,MASCULINO,60
163,2017-0026,2,2017-02-26,2017,2,26,05:15:00,AV. PERITO MORENO Y FOURNIER,AVENIDA,"MORENO, PERITO AV.",...,"MORENO, PERITO AV. y FOURNIER",4,-58.418428,-34.649791,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,FEMENINO,23
164,2017-0026,2,2017-02-26,2017,2,26,05:15:00,AV. PERITO MORENO Y FOURNIER,AVENIDA,"MORENO, PERITO AV.",...,"MORENO, PERITO AV. y FOURNIER",4,-58.418428,-34.649791,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,CONDUCTOR,MASCULINO,19
173,2017-0035,3,2017-03-23,2017,3,23,05:00:00,AV. DR. TRISTAN ACHAVAL RODRIGUEZ Y BLVD. AZUC...,AVENIDA,"ACHAVAL RODRIGUEZ, T., DR. AV.",...,"ACHAVAL RODRIGUEZ, T., DR. AV. y VILLAFLOR, AZ...",1,-58.358815,-34.611136,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,CONDUCTOR,MASCULINO,28
174,2017-0035,3,2017-03-23,2017,3,23,05:00:00,AV. DR. TRISTAN ACHAVAL RODRIGUEZ Y BLVD. AZUC...,AVENIDA,"ACHAVAL RODRIGUEZ, T., DR. AV.",...,"ACHAVAL RODRIGUEZ, T., DR. AV. y VILLAFLOR, AZ...",1,-58.358815,-34.611136,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,MASCULINO,32
175,2017-0035,3,2017-03-23,2017,3,23,05:00:00,AV. DR. TRISTAN ACHAVAL RODRIGUEZ Y BLVD. AZUC...,AVENIDA,"ACHAVAL RODRIGUEZ, T., DR. AV.",...,"ACHAVAL RODRIGUEZ, T., DR. AV. y VILLAFLOR, AZ...",1,-58.358815,-34.611136,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,MASCULINO,30
176,2017-0036,2,2017-03-29,2017,3,29,18:00:00,CURUPAYTI Y COLECTORA AV. GRAL. PAZ,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y CAMPANA",12,-58.514523,-34.581598,MOTO-PASAJEROS,MOTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,FEMENINO,SD
177,2017-0036,2,2017-03-29,2017,3,29,18:00:00,CURUPAYTI Y COLECTORA AV. GRAL. PAZ,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y CAMPANA",12,-58.514523,-34.581598,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,20
186,2017-0050,2,2017-04-28,2017,4,28,11:08:08,AU PERITO MORENO Y RAMAL ENLACE AU1/AU6,AUTOPISTA,AUTOPISTA PERITO MORENO,...,NaN,9,NaN,NaN,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MASCULINO,46
187,2017-0050,2,2017-04-28,2017,4,28,11:08:08,AU PERITO MORENO Y RAMAL ENLACE AU1/AU6,AUTOPISTA,AUTOPISTA PERITO MORENO,...,NaN,9,NaN,NaN,MOTO-CARGAS,MOTO,CARGAS,PASAJERO_ACOMPAÑANTE,MASCULINO,16
237,2017-0108,2,2017-09-02,2017,9,2,04:53:08,AV. GRAL. PAZ Y MACHAIN,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y MACHAIN",12,-58.494911,-34.547956,AUTO-OBJETO FIJO,OBJETO FIJO,AUTO,PASAJERO_ACOMPAÑANTE,MASCULINO,17
238,2017-0108,2,2017-09-02,2017,9,2,04:53:08,AV. GRAL. PAZ Y MACHAIN,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y MACHAIN",12,-58.494911,-34.547956,AUTO-OBJETO FIJO,OBJETO FIJO,AUTO,PASAJERO_ACOMPAÑANTE,MASCULINO,10
242,2017-0112,2,2017-09-10,2017,9,10,09:32:17,AU 25 DE MAYO Y AV. VARELA,AUTOPISTA,AUTOPISTA 25 DE MAYO,...,AUTOPISTA 25 DE MAYO y VARELA AV.,7,-58.458074,-34.639974,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,MASCULINO,1
243,2017-0112,2,2017-09-10,2017,9,10,09:32:17,AU 25 DE MAYO Y AV. VARELA,AUTOPISTA,AUTOPISTA 25 DE MAYO,...,AUTOPISTA 25 DE MAYO y VARELA AV.,7,-58.458074,-34.639974,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,MASCULINO,SD
253,2017-0126,2,2017-10-14,2017,10,14,06:15:00,AV. RIESTRA Y CAÑADA DE GOMEZ,AVENIDA,RIESTRA AV.,...,RIESTRA AV. y CAÃ‘ADA DE GOMEZ,8,-58.480037,-34.681485,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,PASAJERO_ACOMPAÑANTE,MASCULINO,39
254,2017-0126,2,2017-10-14,2017,10,14,06:15:00,AV. RIESTRA Y CAÑADA DE GOMEZ,AVENIDA,RIESTRA AV.,...,RIESTRA AV. y CAÃ‘ADA DE GOMEZ,8,-58.480037,-34.681485,AUTO-OBJETO FIJO,AUTO,OBJETO FIJO,CONDUCTOR,MASCULINO,36
277,2017-0153,2,2017-12-11,2017,12,11,02:00:00,ROSARIO Y AV. LA PLATA,AVENIDA,ROSARIO,...,ROSARIO y LA PLATA AV.,6,-58.428553,-34.618294,MOTO-PASAJEROS,MOTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,MASCULINO,SD
278,2017-0153,2,2017-12-11,2017,12,11,02:00:00,ROSARIO Y AV. LA PLATA,AVENIDA,ROSARIO,...,ROSARIO y LA PLATA AV.,6,-58.428553,-34.618294,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,30
300,2018-0015,2,2018-02-06,2018,2,6,01:00:00,Australia Av. 2800,AVENIDA,AUSTRALIA AV.,...,AUSTRALIA AV. 2800,4,-58.386363,-34.646843,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,28
301,2018-0015,2,2018-02-06,2018,2,6,01:00:00,Australia Av. 2800,AVENIDA,AUSTRALIA AV.,...,AUSTRALIA AV. 2800,4,-58.386363,-34.646843,MOTO-PASAJEROS,MOTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,MASCULINO,19
312,2018-0026,2,2018-03-09,2018,3,9,04:45:00,"Rabanal, Francisco, Intendente Av. y Saenz Av.",AVENIDA,"RABANAL, FRANCISCO, INTENDENTE AV.",...,"RABANAL, FRANCISCO, INTENDENTE AV. y SAENZ AV.",4,-58.416578,-34.654762,MOVIL-CARGAS,MOVIL,CARGAS,CONDUCTOR,MASCULINO,24
313,2018-0026,2,2018-03-09,2018,3,9,04:45:00,"Rabanal, Francisco, Intendente Av. y Saenz Av.",AVENIDA,"RABANAL, FRANCISCO, INTENDENTE AV.",...,"RABANAL, FRANCISCO, INTENDENTE AV. y SAENZ AV.",4,-58.416578,-34.654762,MOVIL-CARGAS,MOVIL,CARGAS,PASAJERO_ACOMPAÑANTE,MASCULINO,30
325,2018-0038,2,2018-04-20,2018,4,20,17:10:00,AV. RIVADAVIA 1571,AVENIDA,RIVADAVIA AV.,...,RIVADAVIA AV. 1571,1,-58.388722,-34.608850,PEATON-AUTO,PEATON,AUTO,PEATON,FEMENINO,59
326,2018-0038,2,2018-04-20,2018,4,20,17:10:00,AV. RIVADAVIA 1571,AVENIDA,RIVADAVIA AV.,...,RIVADAVIA AV. 1571,1,-58.388722,-34.608850,PEATON-AUTO,PEATON,AUTO,PEATON,MASCULINO,61
373,2018-0085,2,2018-08-03,2018,8,3,18:16:00,"Entre Rios Av. y Garay, Juan De Av.",AVENIDA,ENTRE RIOS AV.,...,"ENTRE RIOS AV. y GARAY, JUAN DE AV.",3,-58.391189,-34.627043,MOTO-PASAJEROS,MOTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,FEMENINO,22
374,2018-0085,2,2018-08-03,2018,8,3,18:16:00,"Entre Rios Av. y Garay, Juan De Av.",AVENIDA,ENTRE RIOS AV.,...,"ENTRE RIOS AV. y GARAY, JUAN DE AV.",3,-58.391189,-34.627043,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,30
387,2018-0098,2,2018-09-09,2018,9,9,05:00:00,Av. Gral. Paz e/ Ferre y Beron de Astrada,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y BERON DE ASTRADA",8,-58.471994,-34.696402,AUTO-AUTO,AUTO,AUTO,CONDUCTOR,MASCULINO,55
388,2018-0098,2,2018-09-09,2018,9,9,05:00:00,Av. Gral. Paz e/ Ferre y Beron de Astrada,GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. y BERON DE ASTRADA",8,-58.471994,-34.696402,AUTO-AUTO,AUTO,AUTO,PASAJERO_ACOMPAÑANTE,MASCULINO,54
418,2018-0128,2,2018-11-25,2018,11,25,04:30:00,"Paz, Gral. Av. 11200",GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. 11200",9,-58.528446,-34.645929,AUTO-PASAJEROS,AUTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,MASCULINO,49
419,2018-0128,2,2018-11-25,2018,11,25,04:30:00,"Paz, Gral. Av. 11200",GRAL PAZ,"PAZ, GRAL. AV.",...,"PAZ, GRAL. AV. 11200",9,-58.528446,-34.645929,AUTO-PASAJEROS,AUTO,PASAJEROS,PASAJERO_ACOMPAÑANTE,FEMENINO,39
444,2019-0010,2,2019-02-02,2019,2,2,07:50:00,DEL LIBERTADOR AV. 4100,AVENIDA,DEL LIBERTADOR AV.,...,DEL LIBERTADOR AV. 4100,14,-58.426685,-34.569615,PEATON-AUTO,PEATON,AUTO,PEATON,MASCULINO,SD
445,2019-0010,2,2019-02-02,2019,2,2,07:50:00,DEL LIBERTADOR AV. 4100,AVENIDA,DEL LIBERTADOR AV.,...,DEL LIBERTADOR AV. 4100,14,-58.426685,-34.569615,PEATON-AUTO,PEATON,AUTO,PEATON,MASCULINO,59
576,2020-0038,2,2020-08-30,2020,8,30,04:00:00,"LAS HERAS GENERAL AV. Y DIAZ, CNEL. AV.",AVENIDA,LAS HERAS GENERAL AV.,...,"LAS HERAS GENERAL AV. y DIAZ, CNEL. AV.",14,-58.406175,-34.583459,AUTO-AUTO,AUTO,AUTO,CONDUCTOR,MASCULINO,46
577,2020-0038,2,2020-08-30,2020,8,30,04:00:00,"LAS HERAS GENERAL AV. Y DIAZ, CNEL. AV.",AVENIDA,LAS HERAS GENERAL AV.,...,"LAS HERAS GENERAL AV. y DIAZ, CNEL. AV.",14,-58.406175,-34.583459,AUTO-AUTO,AUTO,AUTO,CONDUCTOR,MASCULINO,64
602,2020-0063,2,2020-12-05,2020,12,5,07:10:00,NUEVA YORK Y ALTA GRACIA,CALLE,NUEVA YORK,...,NUEVA YORK y ALTA GRACIA,11,-58.527838,-34.610470,PEATON_MOTO-MOTO,PEATON_MOTO,MOTO,PEATON,MASCULINO,38
603,2020-0063,2,2020-12-05,2020,12,5,07:10:00,NUEVA YORK Y ALTA GRACIA,CALLE,NUEVA YORK,...,NUEVA YORK y ALTA GRACIA,11,-58.527838,-34.610470,PEATON_MOTO-MOTO,PEATON_MOTO,MOTO,PASAJERO_ACOMPAÑANTE,MASCULINO,21
616,2020-0077,2,2020-12-25,2020,12,25,06:40:00,SAN MARTIN AV. Y PUNTA ARENAS,AVENIDA,SAN MARTIN AV.,...,SAN MARTIN AV. y PUNTA ARENAS,15,-58.472209,-34.601114,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,FEMENINO,30
617,2020-0077,2,2020-12-25,2020,12,25,06:40:00,SAN MARTIN AV. Y PUNTA ARENAS,AVENIDA,SAN MARTIN AV.,...,SAN MARTIN AV. y PUNTA ARENAS,15,-58.472209,-34.601114,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,24

### Cant_Victimas

En esta columna no hay inconvenientes

In [182]:
df_homicidios['Cant_Victimas'].value_counts()

Cant_Victimas
1    676
2     38
3      3
Name: count, dtype: int64

### Fecha, Año, Mes, Día

Se analizan las 3 columnas juntas porque estan relacionadas.

In [203]:
df_homicidios[df_homicidios['Día']!=df_homicidios['Fecha'].dt.day]

,Id_Hecho,Cant_Victimas,Fecha,Año,Mes,Día,Hora,Lugar_Del_Hecho,Tipo_De_Calle,Calle,...,Dirección Normalizada,Comuna,Latitud,Longitud,Participantes,Victima,Acusado,Rol,Sexo,Edad
65,2016-0087,1,2016-07-02,2016,7,3,00:10:00,AUTOPISTA 1 SUR PTE ARTURO FRONDIZI Y AV CASEROS,AUTOPISTA,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI,...,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI y C...,1,-58.378646,-34.629071,MOTO-OBJETO FIJO,MOTO,OBJETO FIJO,CONDUCTOR,MASCULINO,23

In [205]:
df_homicidios[df_homicidios['Mes']!=df_homicidios['Fecha'].dt.month]

Empty DataFrame
Columns: [Id_Hecho, Cant_Victimas, Fecha, Año, Mes, Día, Hora, Lugar_Del_Hecho, Tipo_De_Calle, Calle, Altura, Cruce, Dirección Normalizada, Comuna, Latitud, Longitud, Participantes, Victima, Acusado, Rol, Sexo, Edad]
Index: []

[0 rows x 22 columns]

In [206]:
df_homicidios[df_homicidios['Año']!=df_homicidios['Fecha'].dt.year]

Empty DataFrame
Columns: [Id_Hecho, Cant_Victimas, Fecha, Año, Mes, Día, Hora, Lugar_Del_Hecho, Tipo_De_Calle, Calle, Altura, Cruce, Dirección Normalizada, Comuna, Latitud, Longitud, Participantes, Victima, Acusado, Rol, Sexo, Edad]
Index: []

[0 rows x 22 columns]

Al ver que solo hay diferencia en uno solo de los días hacemos una función para cambiar los dias que sean diferentes.

In [207]:
def cambiar_dia(x):
    return x.dt.day

In [208]:
df_homicidios['Día'][df_homicidios['Día']!=df_homicidios['Fecha'].dt.day] = cambiar_dia(df_homicidios['Fecha'])

C:\Users\juan\AppData\Local\Temp\ipykernel_21976\4151666957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_homicidios['Día'][df_homicidios['Día']!=df_homicidios['Fecha'].dt.day] = cambiar_dia(df_homicidios['Fecha'])

In [209]:
df_homicidios[df_homicidios['Día']!=df_homicidios['Fecha'].dt.day]

Empty DataFrame
Columns: [Id_Hecho, Cant_Victimas, Fecha, Año, Mes, Día, Hora, Lugar_Del_Hecho, Tipo_De_Calle, Calle, Altura, Cruce, Dirección Normalizada, Comuna, Latitud, Longitud, Participantes, Victima, Acusado, Rol, Sexo, Edad]
Index: []

[0 rows x 22 columns]

### Hora

In [212]:
df_homicidios['Hora']=pd.to_datetime(df_homicidios['Hora'], format='%H:%M:%S').dt.time

ValueError: time data "SD" doesn't match format "%H:%M:%S", at position 536. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

Se crea una función para transformar las columnas Latitud y Longitud en float y en el caso de no poder reemplaza el valor por NaN

In [163]:
valores=list()
def transformar_float(x):
    try:
        return float(x)
    except:
        valores.append(x)

In [164]:
df_homicidios['Latitud'] = df_homicidios['Latitud'].apply(transformar_float)

In [165]:
valores

['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']

In [166]:
valores=list()
def transformar_float(x):
    try:
        return float(x)
    except:
        valores.append(x)

In [167]:
df_homicidios['Longitud'] = df_homicidios['Longitud'].apply(transformar_float)

In [168]:
valores

['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']

Como se aprecia los valores que no se puediero convertir en *float* son puntos, por lo que se remplazaran por **None**

In [171]:
def reemplazar(x):
    try:
        return float(x)
    except:
        return None

In [172]:
df_homicidios['Latitud'] = df_homicidios['Latitud'].apply(reemplazar)
df_homicidios['Longitud'] = df_homicidios['Longitud'].apply(reemplazar)

In [173]:
df_homicidios.columns

Index(['Id_Hecho', 'Cant_Victimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora',
       'Lugar_Del_Hecho', 'Tipo_De_Calle', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'Comuna', 'Latitud', 'Longitud',
       'Participantes', 'Victima', 'Acusado', 'Rol', 'Sexo', 'Edad'],
      dtype='object')